render_mode: None   # None, human, rgb_array, rgb_array_float

defaults:
  - algo : PPO
  - env : robo-sumo-ants-v0
  - _self_


hydra:
  job:
    chdir: true
  run:
    dir: ./result/${env}/${now:%m-%d_%H-%M}_${algo}_cleanrl/${hydra.job.override_dirname}