defaults:
  - algo: PPO_cleanrl
  - env: robo-sumo-ants-v0
  - _self_

exp_name: ${algo_name}
render_mode: None   # None, human, rgb_array, rgb_array_float

hydra:
  job:
    chdir: true
  run:
    dir: ./runs/${env_name}/${now:%m-%d_%H-%M}_${algo_name}
  # sweeper:
  #   params:
  #     db: mysql,postgresql
  #     schema: warehouse,support,school