wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715436172
    t:
      1:
      - 1
      - 50
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.8.10
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
