# @package _global_
algo_name: PPO_cleanrl    # PPO

seed: 1
torch_deterministic: True
cuda: True
track: False
wandb_project_name: "evo-competition"
wandb_entity: 计算智能及机器人学
wandb_group: ${env_id}
capture_video: False
save_model: True
upload_model: False
hf_entity: ""

# Algorithm specific arguments
env_id: "robo-sumo-ants-v0"
total_timesteps: 2000000000
learning_rate: 0.001
num_envs: 1600  # 409600/num_steps 1600
num_steps: 256  # 128, 256, 512
anneal_lr: True
gamma: 0.995
gae_lambda: 0.95
num_minibatches: 64
update_epochs: 6
norm_adv: True
clip_coef: 0.2
clip_vloss: True
ent_coef: 0.0 # 0.1
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 0.0

# to be filled in runtime
exp_name: ""
batch_size: 0
minibatch_size: 0
num_iterations: 0

save_model_interval: 500
iteration_alpha_anneal: 500